# GitLab CI/CD Configuration for AI Code Webhook Server
# This pipeline is triggered by the webhook server when @ai is mentioned
# If you drop this into an existing pipeline make sure that only the ai stage is triggered when $AI_TRIGGER is set.

stages:
  - ai

variables:
  # Specify the prebuilt agent image containing the runner and Claude Code CLI
  AI_AGENT_IMAGE: "ghcr.io/schickli/agent-for-gitlab/agent-image:latest"

  # AI_MODEL: Claude model to use (optional, defaults to "sonnet")
  # Options: "sonnet", "opus", "haiku", or full model ID like "claude-sonnet-4-20250514"
  # AI_MODEL: "sonnet"

  # AI_INSTRUCTIONS: Custom system prompt to append to Claude's instructions (optional)
  # AI_INSTRUCTIONS: "You are a helpful coding assistant"

ai_webhook_handler:
  stage: ai
  image: $AI_AGENT_IMAGE
  before_script:
    # Setup Claude Code authentication
    - mkdir -p ~/.claude
    - |
      if [ -n "$CLAUDE_CREDENTIALS" ]; then
        echo "$CLAUDE_CREDENTIALS" > ~/.claude/.credentials.json
      fi
  script:
    - ai-runner
  rules:
    - if: '$AI_TRIGGER == "true"'
  artifacts:
    paths:
      - ai-output.json
    expire_in: 1 week
