# GitLab CI/CD Configuration for AI Code Webhook Server
# This pipeline is triggered by the webhook server when @ai is mentioned

stages:
  - ai

variables:
  # Specify the prebuilt agent image containing the runner and tools
  AI_AGENT_IMAGE: "ghcr.io/schickli/agent-for-gitlab/agent-image:latest"
  # opencode expects provider/model, e.g. anthropic/claude-sonnet-4-20250514 or openrouter/deepseek/deepseek-reasoner
  OPENCODE_MODEL: "anthropic/claude-sonnet-4-20250514"
  OPENCODE_AGENT_PROMPT: |
    You are a helpful assistant that fixes bugs and implements features.
    Always write tests for your changes.
    You have the .Net SDK 8 and Node 24 installed.
    If you did big code changes, you need to test them. (Give up after two failed attempts)
    Follow the project's coding standards.
  TRIGGER_PHRASE: "@AI"

ai_webhook_handler:
  stage: ai
  image: $AI_AGENT_IMAGE
  script:
    - echo "Processing AI webhook trigger..."
    - echo "Project:" ${AI_PROJECT_PATH}
    - echo "Resource Type:" ${AI_RESOURCE_TYPE}
    - echo "Resource ID:" ${AI_RESOURCE_ID}
    - echo "Branch:" ${AI_BRANCH}
    - echo "Author:" ${AI_AUTHOR}
    - git fetch origin ${AI_BRANCH}:${AI_BRANCH} || true
    - git checkout ${AI_BRANCH} || git checkout -b ${AI_BRANCH}
    - ai-runner
  rules:
    - if: '$AI_TRIGGER == "true"'
  artifacts:
    paths:
      - ai-output.json
    expire_in: 1 week
