# GitLab CI/CD Configuration for Claude Code Webhook Server
# This pipeline is triggered by the webhook server when @claude is mentioned

stages:
  - claude

variables:
  # Specify the prebuilt agent image containing the runner and tools
  CLAUDE_AGENT_IMAGE: "ghcr.io/schickli/claude-code-for-gitlab/agent-image:latest"
  CLAUDE_MODEL: "sonnet"
  CLAUDE_INSTRUCTIONS: |
    You are a helpful assistant that fixes bugs and implements features.
    Always write tests for your changes.
    You have the .Net SDK 8 and Node 24 installed.
    If you did big code changes, you need to test them. (Give up after two failed attempts)
    Follow the project's coding standards.
  TRIGGER_PHRASE: "@AI"

claude_webhook_handler:
  stage: claude
  image: $CLAUDE_AGENT_IMAGE
  before_script:
    - echo "Using agent image: $CI_JOB_IMAGE"
  script:
    - echo "Processing Claude webhook trigger..."
    - echo "Project:" ${CLAUDE_PROJECT_PATH}
    - echo "Resource Type:" ${CLAUDE_RESOURCE_TYPE}
    - echo "Resource ID:" ${CLAUDE_RESOURCE_ID}
    - echo "Branch:" ${CLAUDE_BRANCH}
    - echo "Author:" ${CLAUDE_AUTHOR}
    - git fetch origin ${CLAUDE_BRANCH}:${CLAUDE_BRANCH} || true
    - git checkout ${CLAUDE_BRANCH} || git checkout -b ${CLAUDE_BRANCH}
    - claude-runner
  rules:
    - if: '$CLAUDE_TRIGGER == "true"'
  artifacts:
    paths:
      - claude-output.json
    expire_in: 1 week
