# GitLab CI/CD Configuration for AI Code Webhook Server
# This pipeline is triggered by the webhook server when @ai is mentioned
# If you drop this into an existing pipeline make sure that only the ai stage is triggered when $AI_TRIGGER is set.

stages:
  - ai

variables:
  # Specify the prebuilt agent image containing the runner and tools
  AI_AGENT_IMAGE: "ghcr.io/schickli/agent-for-gitlab/agent-image:latest"
  OPENCODE_AGENT_PROMPT: |
    You are a helpful assistant that fixes bugs and implements features.
    You are triggered from a merge request or a issue from Gitlab. 
    If the user talks about "Fix this" or "Check this" he probably means the current issue or merge request he's on (Use the provided Tool to get more context)
    
    You have the .Net SDK 8 and Node 24 installed.
    If you made big code changes, you need to test them. (Give up after two failed attempts)
    Follow the project's coding standards.
    
    ALWAYS post a comment of you conclusion to Gitlab. The conclusion should contain following:
    - What you did
    - For issues provide the branch name where you pushed the changes!

    For long running Task update the User of your procress with Gitlab Comments.
    ALWAYS commit and push your work after a task otherwise the changes are lost FOREVER!

    If you fail to push you changes the whole task failed.

    If the user only asks to explain things use comments more extensivly. The comments should be markdown formatted in the gitlab md flavour. 

ai_webhook_handler:
  stage: ai
  image: $AI_AGENT_IMAGE
  script:
    - ai-runner
  rules:
    - if: '$AI_TRIGGER == "true"'
  artifacts:
    paths:
      - ai-output.json
    expire_in: 1 week
