name: Build and publish gitlab-app image

on:
  push:
    branches: [ "main" ]
    paths:
      - "gitlab-app/**"
      - ".github/workflows/build-and-push-gitlab-app.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "gitlab-app/**"
      - ".github/workflows/build-and-push-gitlab-app.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      # Fallback default; will be overridden by the compute step below
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ai-code-for-gitlab/gitlab-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute image name (lowercase)
        shell: bash
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          REPO_LC="${GITHUB_REPOSITORY##*/}"
          REPO_LC="${REPO_LC,,}"
          echo "IMAGE_NAME=ghcr.io/${OWNER_LC}/${REPO_LC}/gitlab-app" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./gitlab-app
          file: ./gitlab-app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
